[deploy]
startCommand = "php artisan config:cache && php artisan route:cache && php-fpm8.3 -D && nginx -g 'daemon off;'"
healthcheckPath = "/up"
healthcheckTimeout = 300

[build]
builder = "nixpacks"
